Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(copg_rcvip.py:149249): Gdk-CRITICAL **: 01:52:22.401: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
2022-11-24 01:52:22.738571: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
